# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        echo "NEXT_PUBLIC_BACKEND_URL=$(NEXT_PUBLIC_BACKEND_URL)" >> .env
        echo "NEXTAUTH_URL=$(NEXTAUTH_URL)" >> .env
        echo "NEXTAUTH_SECRET=$(NEXTAUTH_SECRET)" >> .env
    - task: Docker@2
      displayName: build docker image
      inputs:
        containerRegistry: 'tps-shd-cr-euw-001'
        repository: 'tps-prd-app-frontend'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: |
          latest

    - task: Docker@2
      displayName: push docker image
      inputs:
        containerRegistry: 'tps-shd-cr-euw-001'
        repository: 'tps-prd-app-frontend'
        command: 'push'
        Dockerfile: '**/Dockerfile'
        tags: |
          latest
